import:
    - 'my_base.yaml'
package: []
define:
  - name: 'Experiment'
    class: Experiment
    structure:
        class: Structure
        builder:
            class: Builder
            model: SegDetectorModel
            model_args:
                backbone: deformable_resnet18
                decoder: SegSpatialScaleDetector
                decoder_args:
                    adaptive: True
                    in_channels: [64, 128, 256, 512]
                    k: 50
                    attention_type: 'scale_channel_spatial'
                loss_class: L1BalanceCELoss

        representer:
            class: SegDetectorRepresenter
            max_candidates: 750
        measurer:
            class: QuadMeasurer
        visualizer:
            class: SegDetectorVisualizer
    train:
        class: TrainSettings
        data_loader:
            class: DataLoader
            dataset: ^train_data
            batch_size: 16
            num_workers: 2
#            pin_memory: False
        checkpoint:
            class: Checkpoint
            start_epoch: 0
            start_iter: 0
            resume: null
        model_saver:
            class: ModelSaver
            dir_path: model
            save_interval: 2000
            signal_path: save
        scheduler:
            class: OptimizerScheduler
            optimizer: "SGD"
            optimizer_args:
                lr: 0.000032
                momentum: 0.9
                weight_decay: 0.0001
            learning_rate:
                class: DecayLearningRate
                epochs: 400
        epochs: 400

    validation: &validate
        class: ValidationSettings
        data_loaders:
            icdar2015:
                class: DataLoader
                dataset: ^validate_data
                batch_size: 1
                num_workers: 16
                collect_fn:
                    class: ICDARCollectFN
        visualize: false
        interval: 4500
        exempt: 1

    logger:
        class: Logger
        verbose: true
        level: info
        log_interval: 450

    evaluation: *validate
